export const LOADING_REPORTS = 'WEEK/REPORTS/LOADING';
export const LOADING_SUCCESS = 'WEEK/REPORTS/LOADING/SUCCESS';
export const LOADING_ERROR = 'WEEK/REPORTS/LOADING/ERROR';
export const SET_REPORTS = 'WEEK/REPORTS/SET';