export const LOADING_AFTERSALE = 'AFTERSALE/LOADING';
export const LOADING_SUCCESS = 'AFTERSALE/LOADING/SUCCESS';
export const LOADING_ERROR = 'AFTERSALE/LOADING/ERROR';
export const SET_DEPARTMENT = 'AFTERSALE/DEPARTMENT/SET';