export const LOADING_AFTERSALE = 'AFTERSALE/LOADING';
export const LOADING_SUCCESS = 'AFTERSALE/LOADING/SUCCESS';
export const LOADING_ERROR = 'AFTERSALE/LOADING/ERROR';
export const SET_DEPARTMENT = 'AFTERSALE/DEPARTMENT/SET';
export const SET_STATUS = 'AFTERSALE/STATUS/SET';
export const SET_FILTERS = 'AFTERSALE/FILTERS/SET';
export const CLEAR_DEPARTMENT = 'AFTERSALE/DEPARTMENT/CLEAR';