export const LOADING_QUOTATION = 'ACHIEVEMENT/QUOTATION/LOADING';
export const LOADING_SUCCESS = 'ACHIEVEMENT/QUOTATION/LOADING/SUCCESS';
export const LOADING_ERROR = 'ACHIEVEMENT/QUOTATION/LOADING/ERROR';
export const SET_QUOTATIONS = 'ACHIEVEMENT/QUOTATION/SET';
