export const LOADING_LOGISTICS = 'LOGISTICS/LOADING';
export const LOADING_SUCCESS = 'LOGISTICS/LOADING/SUCCESS';
export const LOADING_ERROR = 'LOGISTICS/LOADING/ERROR';
export const SET_MINE = 'LOGISTICS/MINE/SET';
export const SET_STATUS = 'LOGISTICS/STATUS/SET';
export const SET_FILTERS = 'LOGISTICS/FILTERS/SET';
export const CLEAR_MINE = 'LOGISTICS/MINE/CLEAR';