export const FETCH_USER_DATA = 'UCENTER/USERINFO/FETCH';
export const SET_USER_DATA = 'UCENTER/USERINFO/SET';
export const MODIFY_PASSWORD = 'UCENTER/MODIFY/PASSWORD';
export const MODIFY_PHONE = 'UCENTER/MODIFY/PHONE';
