export const FETCH_REPORT_DETAIL = 'REPORT/DAY/DETAILS/FETCHING';
export const FETCH_REPORT_SUCCESS = 'REPORT/DAY/DETAILS/FETCHED';
export const FETCH_REPORT_ERROR = 'REPORT/DAY/DETAILS/UNFETCHED';
export const UPDATE_REPORT = 'REPORT/DAY/DETAILS/UPDATE';
export const SET_REPORT = 'REPORT/DAY/DETAILS/SET';