export const LOADING_REPORTS = 'WEEK/REPORTS/DEPARTMENT/LOADING';
export const LOADING_SUCCESS = 'WEEK/REPORTS/DEPARTMENT/LOADING/SUCCESS';
export const LOADING_ERROR = 'WEEK/REPORTS/DEPARTMENT/LOADING/ERROR';
export const SET_REPORTS = 'WEEK/REPORTS/DEPARTMENT/SET';