export const LOADING_DETAILS = 'LOGISTICS/LOADING';
export const LOADING_SUCCESS = 'LOGISTICS/LOADING/SUCCESS';
export const LOADING_ERROR = 'LOGISTICS/LOADING/ERROR';
export const SET_DETAIL = 'LOGISTICS/DETAIL/SET';
