export const LOADING_REPORTS = 'DEPARTMENT/REPORTS/LOADING';
export const LOADING_SUCCESS = 'DEPARTMENT/REPORTS/LOADING/SUCCESS';
export const LOADING_ERROR = 'DEPARTMENT/REPORTS/LOADING/ERROR';
export const SET_REPORTS = 'DEPARTMENT/REPORTS/SET';