export const LOADING_REPORTS = 'WEEK/REPORTS/DETAILS/LOADING';
export const LOADING_SUCCESS = 'WEEK/REPORTS/DETAILS/LOADING/SUCCESS';
export const LOADING_ERROR = 'WEEK/REPORTS/DETAILS/LOADING/ERROR';
export const SET_DETAILS = 'WEEK/REPORTS/DETAILS/SET';