export const LOADING_CUSTOMER = 'ACHIEVEMENT/CUSTOMER/LOADING/LOADING';
export const LOADING_SUCCESS = 'ACHIEVEMENT/CUSTOMER/LOADING/SUCCESS';
export const LOADING_ERROR = 'ACHIEVEMENT/CUSTOMER/LOADING/ERROR';
export const SET_CUSTOMER = 'ACHIEVEMENT/CUSTOMER/SET';